# Generated by Django 2.2.7 on 2021-05-24 04:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('object_id', models.CharField(default='', max_length=50, primary_key=True, serialize=False, verbose_name='主键')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='用户名')),
                ('email', models.EmailField(max_length=254, verbose_name='信箱')),
                ('message', models.CharField(max_length=100, verbose_name='留言訊息')),
                ('createtime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
            ],
            options={
                'verbose_name_plural': '用户留言訊息',
                'db_table': 'user_message',
                'ordering': ('-object_id',),
            },
        ),
    ]
