# Generated by Django 3.1.6 on 2021-03-19 08:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Wedding', '0003_auto_20210319_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='createtime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期'),
        ),
    ]
