# Generated by Django 2.2.7 on 2021-05-31 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UploadFile', '0002_filemodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FileModel',
            new_name='File',
        ),
    ]
