# Generated by Django 2.2.7 on 2021-06-01 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadFile', '0003_auto_20210531_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='id',
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
