# Generated by Django 2.2.7 on 2021-06-01 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UploadFile', '0004_auto_20210601_0021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='upload_time',
            new_name='upload_date',
        ),
    ]
