# Generated by Django 2.2.7 on 2021-05-24 03:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Url', models.TextField()),
                ('Order_Url', models.TextField(blank=True, default='-', null=True)),
                ('Title', models.TextField()),
                ('Weight', models.FloatField(blank=True, default=0.0, null=True)),
                ('Weight_check', models.BooleanField(default=False, verbose_name='Check')),
                ('Is_Special_Item', models.BooleanField(default=False, verbose_name='特貨?')),
                ('Price', models.CharField(max_length=40)),
                ('Purchase_Price_check', models.BooleanField(default=False, verbose_name='Check')),
                ('Selling_Price', models.CharField(blank=True, max_length=20, null=True)),
                ('Options', models.TextField(blank=True, null=True)),
                ('Image1', models.URLField(blank=True, null=True)),
                ('Image2', models.URLField(blank=True, null=True)),
                ('Image3', models.URLField(blank=True, null=True)),
                ('Image4', models.URLField(blank=True, null=True)),
                ('Image5', models.URLField(blank=True, null=True)),
                ('Image6', models.URLField(blank=True, null=True)),
                ('Image7', models.URLField(blank=True, null=True)),
                ('Image8', models.URLField(blank=True, null=True)),
                ('Image9', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Update_Time', models.DateField(default=datetime.date.today)),
                ('Weight_Unit_Price', models.FloatField(blank=True, default=13.8, null=True, verbose_name='重量單價/1kg(普)')),
                ('Weight_Unit_Price_Special', models.FloatField(blank=True, default=19, null=True, verbose_name='重量單價/1kg(特)')),
                ('Exchange_Rate', models.FloatField(blank=True, default=4.6, null=True, verbose_name='匯率')),
                ('Creditcard_Fee', models.FloatField(blank=True, default=1.03, null=True, verbose_name='信用卡手續費')),
                ('Transaction_Fee', models.FloatField(blank=True, default=0.0149, null=True, verbose_name='成交手續費(蝦皮)')),
                ('PaybyCard_Fee', models.FloatField(blank=True, default=0.015, null=True, verbose_name='信用卡交易手續費(蝦皮)')),
                ('List_price_Rate', models.FloatField(blank=True, default=1.3, null=True, verbose_name='加成倍數')),
            ],
        ),
    ]
