# Generated by Django 2.2.7 on 2021-05-24 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Purchase_Date', models.DateField()),
                ('Type', models.CharField(blank=True, max_length=5, null=True)),
                ('Weight', models.FloatField(blank=True, null=True)),
                ('Estimated_Weight', models.FloatField(blank=True, null=True)),
                ('shipment_Num', models.CharField(blank=True, max_length=15, null=True)),
                ('goodsname', models.CharField(max_length=15)),
                ('specification', models.CharField(blank=True, max_length=15, null=True)),
                ('Buyer1', models.CharField(blank=True, max_length=15, null=True)),
                ('Buyer2', models.CharField(blank=True, max_length=15, null=True)),
                ('Buyer3', models.CharField(blank=True, max_length=15, null=True)),
                ('Buyer4', models.CharField(blank=True, max_length=15, null=True)),
                ('Buyer5', models.CharField(blank=True, max_length=15, null=True)),
                ('Stock1', models.CharField(blank=True, max_length=15, null=True)),
                ('Stock2', models.CharField(blank=True, max_length=15, null=True)),
                ('Stock3', models.CharField(blank=True, max_length=15, null=True)),
                ('Stock4', models.CharField(blank=True, max_length=15, null=True)),
                ('Stock5', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('Status_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stock_Name', models.CharField(max_length=30)),
                ('Inventory_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Order.Inventory')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Buyer', models.CharField(max_length=30)),
                ('Inventory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Order.Inventory')),
                ('Status', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='Order.OrderStatus')),
            ],
        ),
    ]
